#!/usr/bin/bash

# kill the process if SensorRecord.PID file exists.
# Works (restarts) if the pid file still exist but process is not running
# (eg, if the system was powered down), but gives an error message from kill.

#This can be added to cron (crontab -e) with lines
#   @reboot   ~/startSensorRecord
#   @monthly  ~/startSensorRecord

if [ -f SensorRecord.PID ]; then
    source SensorRecord.PID
    if [ -n "$PID" ]; then
        kill  $PID ;  
        fi
    fi

# restart and write new pid to SensorRecord.PID
source LoRaVenv/bin/activate
./SensorRecord  --filename='SensorRecordOuput_'${HOSTNAME}'_'`date --utc +'%Y-%m'`'.txt' &
echo PID=$! > SensorRecord.PID
