#!/bin/bash

# ../README.md###Database gives a generic description of this script.

# In addition to arguments, this script uses files 
# - SensorIdHash.txt - manually edited for any new sensors installed.
# - ModuleIdHash.txt - manually edited to add description for any new modules.
#
# Subdirectory tmp/ is not kept.
#
# Subdirectory intermediate/ has files prepared for arguments ${1} and &{2}.
# These files should not need to be reproduced frequently. Versions might be
# kept in git as they could be useful for reproducing results and debugging.
#
# Before running this script:
#
# 1/ Prepare the sensor recordings in a .txt file used as argument ${1}
#    (eg intermediate/All_data.txt), This file is built with data  
#    copied from basestation(s):
#    - Copy SensorRecordOuput*.txt files from basestation(s) to raw_data/.
#    - Put all SensorRecord files into one file with
#          cat raw_data/SensorRecordOuput*.txt >intermediate/All_data.txt
#       [If there is only one file then copy it to intermediate/. ]
#  -   Optionally run through SensorDataFreqFilter to reduce frequency, for example
#          cat raw_data/SensorRecordOuput*.txt | \
#              ../utils/SensorDataFreqFilter  30   >intermediate/All_data.txt
#      This drops readings so there is at least 1/2 hour between readings for a module.
#      (Beware that runTests will indicate differences because the test sample is changed.)
#
# 2/ Prepare the sensor locations in a .txt file used as argument ${2}.
#    (eg. intermediate/sensorLocations.txt). This file will not change
#    once hardware in the building is fully installed. 
#    Next requires having once in utils/  done  `python3 -m venv  Rhino3dm`
#    and  pip install rhino3dm in that environment.
#
#    The .txt file information is extracted from the .3dm by python program 
#    extract3dmSensorLocations and written to intermediate/sensorLocations.txt.
#       mkdir -p intermediate
#       source ../utils/Rhino3dm/bin/activate  # activate python environment
#
#       ../utils/extract3dmSensorLocations garage_sensors.3dm >intermediate/sensorLocations.txt
#
#       deactivate    
#    
#    [The file sensorLocations.txt can be edited if necessary, to fix errors
#     in any location information in the .3dm file.]

if [ $# -ne 3 ]; then 
  echo Error. Needs 3 arguments indicating 
  echo   1/ the source txt file of data readings, 
  echo   2/ the source txt file of sensor locations, and
  echo   3/ target database file.
  echo Example: ../utils/buildDB  intermediate/All_data.txt   intermediate/sensorLocations.txt  target/SensorReadings.db
  exit 1
fi;

export SRC=${1}
export SLOC=${2}
export DB=${3}

mkdir -p intermediate
mkdir -p target
mkdir -p tmp

echo "*************** building" ${DB}

# rm old tmp files, 
   rm -f    ${DB}  tmp/All_data.csv  tmp/zzz.csv

echo  Filter and convert module Id and J# to sensor ID, output to .csv ...
   ../utils/SensorDataReformat  --SensorHash='SensorIdHash.txt'  \
           --infile=${SRC}  --outfile='tmp/zzz.csv' 

echo Load csv file of sensor readings into db ...
   ../utils/loadReadings --infile='tmp/zzz.csv' --outdb=${DB}


echo Load sensor ID, location, module, etc into  db ...
   ../utils/loadSensors    \
         --sensorLocations=${SLOC}  \
         --SensorIdHash='SensorIdHash.txt' \
         --ModuleIdHash='ModuleIdHash.txt' --outdb=${DB}

echo done load.

# NOTE THAT ABOVE IS GENERIC AS LONG AS NAMING CONVENTION IS RESPECTED.
# BUT  runTests is specific to a building.
echo Now run tests with
echo "    ./runTests ${DB}"
