#!/bin/bash

# Compare ../README.md###Database, which gives generic description of the
# following script. This script
# 1/ Reads  sensor recordings from a .txt file given by argument ${1}.
#       The source txt ${1} is built from raw_data/SensorRecordOuput*.txt 
#       which are copied from basestation(s).
# 2/ Reads sensor locations from (Rhino) 3dm file ${2}. The sensor locations
#        are extracted by python program extract3dmSensorLocations and 
#        written to file intermediate/sensorLocations.txt.
# 3/ Writes the database file given by ${3}.
#
# The script also uses files 
# - SensorIdHash.txt - manually edited for any new sensors installed.
# - ModuleIdHash.txt - manually edited to add description for any new modules.
#
# Before running this script:
#  -   Copy SensorRecordOuput*.txt files from basestation(s) to raw_data/.
#  -   Put all SensorRecord files into a file, eg intermediate/All_data.txt,  with
#          cat raw_data/SensorRecordOuput*.txt >intermediate/All_data.txt
#       [If there is only one file then copy it to intermediate/. ]
#  -   Optionally run through SensorDataFreqFilter to reduce frequency, for example
#          cat raw_data/SensorRecordOuput*.txt | \
#              ../utils/SensorDataFreqFilter  30   >intermediate/All_data.txt
#      This drops readings so there is at least 1/2 hour between readings for a module.
#      (Beware that runTests will indicate differences because the test sample is changed.)


# Subdirectory intermediate/ has files that might be kept in git as they could be
#   useful for reproducing results and debugging. Subdirectory tmp/ is not kept.


if [ $# -ne 3 ]; then 
  echo Error. Needs 3 arguments indicating 
  echo   1/ the source txt file of data readings, 
  echo   2/ 3dm file with sensor locations, and
  echo   3/ target database file.
  echo Examples: ../utils/buildDB  intermediate/All_data.txt     slab_sensors.3dm   target/SensorReadings.db
  echo           ../utils/buildDB  intermediate/All_data.txt   garage_sensors.3dm   target/SensorReadings.db
  exit 1
fi;

export SRC=${1}
export F3DM=${2}
export DB=${3}

mkdir -p intermediate
mkdir -p target
mkdir -p tmp

echo "*************** building" ${DB}

# rm old tmp files, 
   rm -f    ${DB}  tmp/All_data.csv  tmp/zzz.csv

# if All_data.txt is constructed here by next two lines then optional FreqFilter is not possible.
# echo Put all SensorRecord files into ${SRC}  ...
# cat raw_data/SensorRecordOuput*.txt >${SRC}

echo  Filter and convert module Id and J# to sensor ID, output to .csv ...
   ../utils/SensorDataReformat  --SensorHash='SensorIdHash.txt'  \
           --infile=${SRC}  --outfile='tmp/zzz.csv' 

echo Load csv file of sensor readings into db ...
   ../utils/loadReadings --infile='tmp/zzz.csv' --outdb=${DB}

echo extract sensor locations from .3dm file and write sensorLocations.txt ...
   # next requires having once in utils/  done  `python3 -m venv  Rhino3dm`
   # and  pip install rhino3dm in that environment.

   mkdir -p intermediate
   source ../utils/Rhino3dm/bin/activate  # activate python environment

   ../utils/extract3dmSensorLocations ${F3DM} >intermediate/sensorLocations.txt

   deactivate    

echo Load sensor ID, location, module, etc into  db ...
   ../utils/loadSensors    \
         --sensorLocations='intermediate/sensorLocations.txt'  \
         --SensorIdHash='SensorIdHash.txt' \
         --ModuleIdHash='ModuleIdHash.txt' --outdb=${DB}

echo done load.

# NOTE THAT ABOVE IS GENERIC AS LONG AS NAMING CONVENTION IS RESPECTED.
# BUT  runTests is specific to a building.
echo Now run tests with
echo "    ./runTests ${DB}"
