#!/bin/bash

# writes file  DB=target/SensorReadings.db

# uses files 
#     SensorIdHash.txt - manually edited for any new sensors installed.
#     ModuleIdHash.txt - manually edited to add description for any new modules.
#     sensorLocations.txt - extracted from .3dm drawing by script extractSensorIDLocations.ghx
#     raw_data/SensorRecordOuput*.txt - copied from basestation(s) 

# Then to produce the database run this script
#   ../buildDB

mkdir -p target
mkdir -p tmp

export DB="target/SensorReadings.db"

echo "*************** building" ${DB}

# rm files, but touch ensures it exists so rm doesn't cause error
touch  ${DB} tmp/All_data.txt tmp/All_data.csv 
rm     ${DB} tmp/All_data.txt tmp/All_data.csv

echo Put all SensorRecord files into tmp/All_data.txt  ...
cat raw_data/SensorRecordOuput*.txt >>tmp/All_data.txt

echo  Filter and convert module Id and J# to sensor ID, output to .csv ...
../utils/SensorDataReformat  --SensorHash='SensorIdHash.txt'  \
         --infile='tmp/All_data.txt'  --outfile='tmp/All_data.csv' 

echo Load csv file into db ...
../utils/loadReadings --infile='tmp/All_data.csv' --outdb=${DB}

echo Load sensor ID, location, module, etc into  db ...
../utils/loadSensors  --sensorLocations='sensorLocations.txt' --SensorIdHash='SensorIdHash.txt' \
         --ModuleIdHash='ModuleIdHash.txt' --outdb=${DB}

# NOTE THAT ABOVE IS GENERIC AS LONG AS NAMING CONVENTION IS RESPECTED.
# IT COULD BE IN utils AND USED FOR House/.
# BUT NEXT runTests is specific to Garage/.
echo done load. Running tests ...
./runTests
