#!/bin/bash

if [ $# -lt 1 ]; then 
  echo Error. Needs 1 arguments indicating the database file!
  exit 1
fi;

export DB=${1}

mkdir -p tmp

echo "*************** testing" ${DB}
echo "*** comparison results from SensorReadings_2026-01-19.db ***"

echo 
echo "*** Data Summary - expect changes if testing with different data ***"

echo -n sql_test0.sql ... 
sqlite3 ${DB} <tests/sql_test0.sql  >tmp/sql_test0_out.txt
echo "      diff:"
diff tests/sql_test0_out.txt_result  tmp/sql_test0_out.txt

echo 
echo "*** These should have no changes if the original sample is a subset of new data ***"

export SQL=" sql_test1 sql_test2 sql_test3 "       
export  PY=" test1 test2 test3 "  

for tst in $SQL ; do
  echo -n ${tst}.sql ... 
  sqlite3 ${DB} <tests/${tst}.sql  >tmp/${tst}_out.txt
  echo -n "      diff:"
  diff tests/${tst}_out.txt_result  tmp/${tst}_out.txt
  if [ $? -ne 0 ]; then
      echo "";
  else
      echo "ok";
  fi
  done

for tst in $PY ; do
  echo -n ${tst}.py ... 
  python3 tests/${tst}.py --dbName=${DB} >tmp/${tst}_out.txt
  echo -n "      diff:"
  diff     tests/${tst}_out.txt_result    tmp/${tst}_out.txt
  if [ $? -ne 0 ]; then
      echo "";
  else
      echo "ok";
  fi
  done
