#!/bin/bash

mkdir -p tmp

export DB="target/SensorReadings.db"

echo "*************** testing" ${DB}
echo "****** comparison results from SensorReadings_2026-01-19.db"

echo -n sql_test1.sql ... 
sqlite3 ${DB} <tests/sql_test1.sql  >tmp/sql_test1_out.txt
echo "      diff:"
diff tests/sql_test1_out.txt_result  tmp/sql_test1_out.txt

echo -n sql_test2.sql ...
sqlite3 ${DB} <tests/sql_test2.sql  >tmp/sql_test2_out.txt
echo "      diff:"
diff tests/sql_test2_out.txt_result  tmp/sql_test2_out.txt

echo -n sql_test3.sql ... 
sqlite3 ${DB} <tests/sql_test3.sql  >tmp/sql_test3_out.txt
echo "      diff:"
diff tests/sql_test3_out.txt_result  tmp/sql_test3_out.txt


echo -n test1.py ... 
python3 tests/test1.py --dbName=${DB} >tmp/test1_out.txt
echo "      diff:"
diff     tests/test1_out.txt_result    tmp/test1_out.txt

echo -n test2.py ... 
python3 tests/test2.py --dbName=${DB} >tmp/test2_out.txt
echo "      diff:"
diff     tests/test2_out.txt_result    tmp/test2_out.txt

echo -n test3.py  ...
python3 tests/test3.py --dbName=${DB} >tmp/test3_out.txt
echo "      diff:"
diff     tests/test3_out.txt_result    tmp/test3_out.txt
